version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 21
    commit-message:
      prefix: "[chore]"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    # Group minor and patch updates together
    groups:
      dev-dependencies:
        patterns:
          - "@clack/prompts"
          - "@playwright/test"
          - "@types/*"
          - "@typescript-eslint/*"
          - "@vscode/test-electron"
          - "@vscode/vsce"
          - "esbuild"
          - "eslint*"
          - "npm-run-all"
          - "picocolors"
          - "react"
          - "react-dom"
          - "typescript"
          - "typescript-eslint"
          - "knip"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "@codemirror/language"
          - "@codemirror/language-data"
          - "@codemirror/merge"
          - "@jupyterlab/rendermime"
          - "@tanstack/react-virtual"
          - "@uiw/codemirror-theme-github"
          - "@uiw/react-codemirror"
          - "@vscode/markdown-it-katex"
          - "dompurify"
          - "immer"
          - "katex"
          - "markdown-it"
          - "ws"
          - "zustand"
        exclude-patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 21
    commit-message:
      prefix: "[CI]"
